In [26]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.linear_model import LinearRegression, Lasso

### 导入影响gdp增速的协变量数据

In [27]:
df_all = pd.read_csv('C:/Users/administrator/desktop/codeblocks/94-1802.csv', encoding='gbk', header=None)

In [28]:
df_all = df_all.T

In [29]:
df_all.columns = df_all.iloc[0,:]

In [30]:
df_all = df_all.drop([0])

In [31]:
df_all = df_all.fillna(df_all.mean())

In [32]:
df_all

0     工  业    建筑业    批发零售餐饮业    运输邮电仓储业    金融保险业    房地产业    其他服务业  第一产业  第二产业  \
1     27.0   13.8       13.0       10.8     14.6     6.8     13.3  15.0  26.1   
2     21.2   12.8       16.6       11.6     10.9     6.0      5.2  14.3  20.3   
3     24.5   14.0       13.9        6.5     21.6     8.0     16.2   8.2  23.4   
4     34.0   13.8       19.5        7.8     21.6    14.9     26.3   4.5  31.9   
5     17.4    8.1       14.0       12.3     14.5     7.0     16.2  18.2  16.8   
6     16.8   12.5       15.3        9.2     11.4     7.0     10.3  14.2  16.4   
7     17.0    7.0       13.3        8.9      9.4     5.0      8.5  16.8  16.1   
8     21.2   10.0       13.0        8.5     10.2     9.0      6.3  13.5  20.2   
9     22.8   -3.0       14.0        7.0      3.0     5.0      7.2   3.8  21.3   
10    19.2   -2.8       12.8        7.6      3.4     5.0      8.9   6.5  17.5   
11    17.8   -1.5       13.2        9.0      3.8     5.1      9.1   8.7  16.3   
12    18.9    7.0       11.2       11.3      7.6     7.3      9.1   6.5  17.8   
13    14.8    7.5       18.0        5.3     18.4     8.1     13.0  10.5  14.4   
14    12.6    8.6       15.3        4.7     12.0     7.5     14.5  10.8  12.3   
15    11.8   20.2       15.2       12.8     12.0     8.3     15.9  10.0  12.5   
16    14.1   13.8       17.0       13.3      9.5    10.9     17.0   9.0  14.1   
17     7.9    3.6        7.0        7.2      9.6     9.0     15.2   6.7   7.7   
18     7.5   15.9        5.4       13.5      5.0    17.0     21.4  -3.2   8.0   
19     9.6   13.5        6.6       13.5      4.0    16.5     19.6   0.6   9.9   
20     9.7   13.0        7.2       14.1      3.6    19.4     20.0   2.3  10.0   
21     8.9   20.6        7.9       11.2      3.0    17.2      4.7   7.5   9.5   
22     8.2   15.0        8.6       10.0      4.0    15.2      3.1  10.5   8.8   
23     7.8   14.3        8.8        9.8      4.2    16.0      9.4   8.2   8.4   
24     6.3   14.2        8.9       11.0      4.4    14.4     10.7   8.5   7.0   
25     7.1   18.9        8.1        9.2      3.0     9.6     10.0   3.5   7.8   
26     7.7   18.7        9.2       15.0      4.9    16.1     10.6  -1.0   8.6   
27     8.5   18.9        9.4       12.6      5.2    16.1      8.4   0.5   9.6   
28     9.2   15.5        9.7       11.8      6.8    15.6      8.5   1.2   9.9   
29    12.4   -5.0        8.5       10.2      5.5     8.4      9.7   4.5  10.3   
30    11.3    8.6        8.0       10.1      5.1     8.1     11.1   4.5  10.9   
..     ...    ...        ...        ...      ...     ...      ...   ...   ...   
68    21.9   13.6       14.0        9.6      7.9     0.3     11.3   4.5  20.7   
69    19.3   11.0       12.1        9.9     10.0     8.3     10.9   2.3  18.2   
70    19.4   10.1       12.5        9.8      8.1     2.2     10.9   3.0  17.9   
71    20.0    9.6       12.7       10.0      6.0     9.5     12.3   3.0  18.4   
72    19.6    9.3       12.3       10.0      5.5     7.4     10.9   4.0  17.9   
73    16.3   12.5       10.3        6.7     15.0     2.2      9.1   3.1  15.8   
74    15.8   10.4       10.2        7.6     13.4     3.6      9.8   4.3  15.0   
75    14.7   10.8       10.7        7.9     15.2     4.0     11.2   5.1  14.2   
76    15.3    9.1       11.9        8.2     16.5     5.7     11.8   5.5  14.4   
77    13.7   11.2        9.8        7.9     11.0    11.1      7.9   4.0  13.4   
78    13.6    9.0        9.5        7.5     13.2    11.8      8.4   3.0  13.0   
79    13.3    7.1        9.4        7.1     16.9    12.3      7.4   3.6  12.5   
80    13.3    6.7        9.3        7.2     17.5    12.2      7.9   3.5  12.4   
81    12.5    2.8        9.4        6.8     13.4     7.5      5.3   3.6  11.3   
82    11.8    4.5        9.2        5.6     14.2     5.9      7.3   3.9  10.8   
83    11.0    5.2        9.1        6.1     12.9     4.7      7.8   4.5  10.2   
84    10.8    7.1        8.7        6.2     13.6     3.8      9.7   4.6  10.3   
85     8.9    7.4        6.7   

### 导入预测出的下一期数据

In [33]:
data_fit = pd.read_csv('C:/Users/administrator/desktop/codeblocks/inf_data_2017.1.csv', encoding='gbk')

In [34]:
data_fit['.rownames'] = df_all.columns[:-1]

In [35]:
data_fit

Unnamed: 0  .rownames   t   y    .fitted   .se.fit  .resids  .std.resid  \
0          93       工  业  93 NaN   8.398434  2.678509        0         NaN   
1         186        建筑业  93 NaN   5.619864  5.223378        0         NaN   
2         279    批发零售餐饮业  93 NaN   6.596209  1.992200        0         NaN   
3         372    运输邮电仓储业  93 NaN   3.691571  3.144399        0         NaN   
4         465      金融保险业  93 NaN  14.935027  3.177645        0         NaN   
5         558       房地产业  93 NaN  12.452377  3.095617        0         NaN   
6         651      其他服务业  93 NaN  12.959555  4.629461        0         NaN   
7         744       第一产业  93 NaN   2.557817  3.092085        0         NaN   
8         837       第二产业  93 NaN   7.994720  2.310379        0         NaN   
9         930       第三产业  93 NaN  10.544607  1.665360        0         NaN   

   .conf.low   .conf.up  
0   3.148653  13.648216  
1  -4.617768  15.857496  
2   2.691570  10.500849  
3  -2.471338   9.854479  
4   8.706957  21.163098  
5   6.385079  18.519674  
6   3.885977  22.033133  
7  -3.502558   8.618191  
8   3.466460  12.522979  
9   7.280561  13.808652

### 方案一：先做特征选择再做回归预测

In [36]:
nn = 5

In [37]:
out = SelectKBest(f_regression, k=nn).fit(df_all.iloc[:,:-1],df_all.iloc[:,-1])

In [38]:
df_all.columns[np.argsort(-out.scores_)[:nn]]

Index(['第二产业', '  工  业', '  批发零售餐饮业', '第一产业', '第三产业'], dtype='object', name=0)

In [39]:
X_new = SelectKBest(f_regression, k=nn).fit_transform(df_all.iloc[:,:-1],df_all.iloc[:,-1]);X_new

array([[27. , 13. , 15. , 26.1, 11.8],
       [21.2, 16.6, 14.3, 20.3, 10. ],
       [24.5, 13.9,  8.2, 23.4, 13.9],
       [34. , 19.5,  4.5, 31.9, 18.4],
       [17.4, 14. , 18.2, 16.8, 13.1],
       [16.8, 15.3, 14.2, 16.4, 11.4],
       [17. , 13.3, 16.8, 16.1,  9.8],
       [21.2, 13. , 13.5, 20.2,  9.5],
       [22.8, 14. ,  3.8, 21.3,  8.3],
       [19.2, 12.8,  6.5, 17.5,  8.4],
       [17.8, 13.2,  8.7, 16.3,  9. ],
       [18.9, 11.2,  6.5, 17.8,  9.8],
       [14.8, 18. , 10.5, 14.4, 13.2],
       [12.6, 15.3, 10.8, 12.3, 11.5],
       [11.8, 15.2, 10. , 12.5, 13.6],
       [14.1, 17. ,  9. , 14.1, 14.3],
       [ 7.9,  7. ,  6.7,  7.7,  9.5],
       [ 7.5,  5.4, -3.2,  8. , 12.5],
       [ 9.6,  6.6,  0.6,  9.9, 12.1],
       [ 9.7,  7.2,  2.3, 10. , 12.7],
       [ 8.9,  7.9,  7.5,  9.5,  8.1],
       [ 8.2,  8.6, 10.5,  8.8,  7.6],
       [ 7.8,  8.8,  8.2,  8.4,  9.5],
       [ 6.3,  8.9,  8.5,  7. , 10. ],
       [ 7.1,  8.1,  3.5,  7.8,  8.3],
       [ 7.7,  9.2, -1. ,

In [45]:
# 列名需要对照数据输入
col = np.array(['第二产业', '  工  业', '  批发零售餐饮业', '第一产业', '第三产业'])

In [46]:
Y = np.array(df_all.iloc[:,-1])

In [47]:
model = LinearRegression()
model.fit(X_new, Y)
model.score(X_new, Y)

0.9728999849357034

In [48]:
x_new = np.array([data_fit.loc[[True if x in col else False for x in data_fit['.rownames']],'.fitted']]);x_new

array([[ 8.3984343 ,  6.59620902,  2.55781683,  7.99471996, 10.54460664]])

In [49]:
model.predict(x_new)

array([8.07827352])